### ISSUE TITLE
Define needed JSON API

### ISSUE THREAD

**Issue by yannbolliger** [EfficaceFood/efficace-android#1]

**Comment by yannbolliger** [comment]
Your document is very nice. Thanks.
I think the next thing to add is the diffrent POST requests so that the user can update the profile, its chosen stuff etc.

**Comment by yannbolliger** [comment]
@cmacmillan1 @dominicrawlins Please complete the API and put it as a Markdown on the efficace-server repo, so that we can work with it.

**Comment by cmacmillan1** [comment]
@yannbolliger I've made some changes to the API and added it as a markdown. The drive version is no longer valid. 

If you need anymore info let me know, but this is all that's needed for the android app, I believe.
